### ISSUE TITLE
Fix and improvements

### ISSUE THREAD

**Issue by lmorente** [MasterCloudApps-Projects/chess#4]
## Top priority
- [x] Different object implementations in JS (documentation and example project)
- [x] Define enums in JS

[tfmCodeDoc](https://github.com/joseramosvalderrama/tfmCodeDocu)

### Tasks
- [x] 0 - Add moveRule template method pattern to documentation
  - [x] 0.1 - Add decorator pattern to documentation 
- [x] 1 - Fix rejected inheritance (pawn), maybe by using a correct decorator pattern
- [x] 2 - Rename CPUPlayer to randomCPU
- [x] 3 - Move CPU player to front end
- [x] ~4 - Do Class diagram~ (let's do this later since project structure will probably still change)
- [x] 5 - Rename chess folder to backend, and proyect name to chess. 
- [x] 6 & 7 - Improve project packages 
- [x] 8 - Merge pieces factory by color
- [x] 9 - Define Enums in PieceType
- [x] 10 - Object-oriented front end
- [x] 11 - Update patterns in the readme
- [x] 12 - Create a single generic method for get piece (delete getRook, getHorse ...)
- [x] 13 - Rename movements to rules (Example MovementRules)
- [x] 14 - Refactor coordinate system & abstractMoveRule to make it simpler (ref https://github.com/x-USantaTecla-game-chess/java.swing.socket.sql/tree/master/src/usantatecla)
- [x] 15 - Make memento reuse board builder methods

[More information in the task description](https://docs.google.com/document/d/1C_jCO1vq12GdECJUEXQ1npqXaakF_9yX9OSTb3g2OMQ/edit)

### Fix
- [x] Fix Memento: save turn (now undo / redo each player movement)

**Comment by LuisBoto** [comment]
All tasks are done so i'll be opening a Pull Request. Minor changes that are needed can be added while it's open, and we can request a review on the whole project by the tutor.
